containers:
  analysis: docker://ghcr.io/clelange/reana-demo-bsm-search:2.0.0
  root: docker://ghcr.io/clelange/root:6.38.04-ubuntu24.04

workdir: work

# Set to -1 to use Python's non-deterministic default seeding.
random_seed: 12345

data:
  nevents: [20000, 20000, 20000, 20000, 20000]
  qcd_transfer_factor: 0.1875
  control_region_fraction: 0.8
  qcd_fraction: 0.75
  qcd_generator:
    loc: 5
    scale: 4

signal:
  nevents: [40000, 40000]
  weight: 0.0025
  generator:
    loc: 1
    scale: 0.5

backgrounds:
  mc1:
    nevents: [40000, 40000, 40000, 40000]
    weight: 0.01875
    data_fraction: 0.15
    generator:
      loc: -3
      scale: 1.5
  mc2:
    nevents: [40000, 40000, 40000, 40000]
    weight: 0.0125
    data_fraction: 0.1
    generator:
      loc: -1
      scale: 0.9

systematics:
  weight:
    weight_var1:
      up:
        name: weight_var1_up
        factor: 1.05
      down:
        name: weight_var1_dn
        factor: 0.95
  shape:
    shape_conv:
      up:
        name: shape_conv_up
        shift: [0, 1]
      down:
        name: shape_conv_dn
        shift: [-1, 0]
