# If you would like to test the analysis locally (i.e. outside of the REANA
# platform), you can proceed as follows:
#
#   $ pip install yadage
#   we can now run the analysis workflow
#   $ yadage-run _run workflow/databkgmc.yml
#   let up check output files
#   $ ls -l _run/plot/*.pdf
#   -rw-r--r-- 1 root root 19193 May 16 15:34 _run/plot/postfit.pdf
#   -rw-r--r-- 1 root root 19450 May 16 15:34 _run/plot/prefit.pdf

stages:
  - name: all_bkg_mc
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        mcname: [mc1,mc2]
        mcweight: [0.01875,0.0125]  # [Ndata / Ngen * 0.2 * 0.15,  Ndata / Ngen * 0.2 * 0.1] = [10/16*0.03, 1/16 * 0.02]
        nevents:  [40000,40000,40000,40000]  #160k events / mc sample
      workflow: {$ref: workflow/wflow_all_mc.yml}
  - name: data
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        nevents: [20000,20000,20000,20000,20000]
      workflow: {$ref: workflow/workflow_data.yml}
  - name: signal
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        nevents: [40000,40000]
        mcweight: 0.0025 #Ndata / Ngen * 0.2 * 0.1] = [100/80 * 0.2 * 0.05]
      workflow: {$ref: workflow/workflow_sig.yml}
  - name: merge
    dependencies: [all_bkg_mc,data,signal]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        background: {stages: 'all_bkg_mc[*].merge', output: mergedfile, unwrap: true}
        data: {stages: 'data[*].mergeall', output: mergedfile, unwrap: true}
        signal: {stages: 'signal[*].hist_merge', output: mergedfile, unwrap: true}
        mergedfile: '{workdir}/merged.root'
      step: {$ref: workflow/steps.yml#/merge_root_allpars}
  - name: makews
    dependencies: [merge]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        data_bkg_hists: {stages: 'merge', output: mergedfile, unwrap: true}
        workspace_prefix: '{workdir}/results/workspace'
        xml_dir: '{workdir}/xmldir'
      step: {$ref: workflow/steps.yml#/makews}
  - name: plot
    dependencies: [makews]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        combined_model: {stages: 'makews', output: workspace, unwrap: true}
        nominal_vals: '{workdir}/nominal_vals.yml'
        fit_results: '{workdir}/fit_results.yml'
        prefit_plot: '{workdir}/prefit.pdf'
        postfit_plot: '{workdir}/postfit.pdf'
      step: {$ref: workflow/steps.yml#/plot}
  - name: hepdata
    dependencies: [makews]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        combined_model: {stages: 'makews', output: workspace, unwrap: true}
        hepdata_submission_zip: '{workdir}/submission.zip'
        hepdata_submission_yaml: '{workdir}/submission.yaml'
        hepdata_data1_yaml: '{workdir}/data1.yaml'
      step: {$ref: workflow/steps.yml#/hepdata}
