# This file is part of REANA.
# Copyright (C) 2020, 2021 CERN.
#
# REANA is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install --pre reana-client

      - name: Build analysis environment image
        run: docker build -f environments/reana-demo-bsm-search/Dockerfile -t reanahub/reana-demo-bsm-search .

      - name: Validate workflow specification file
        run: reana-client validate

      - name: Test whether the ROOT version is well 6
        run: docker run -i --rm -v `pwd`/code:/code reanahub/reana-demo-bsm-search root-config --version | grep -q ^6

      - name: Test whether we can import hftools Python library
        run: docker run -i --rm -v `pwd`/code:/code reanahub/reana-demo-bsm-search /bin/bash -c 'source /usr/local/bin/thisroot.sh && python -c "import hftools.hepdata"'

      - name: Test whether the latest analysis code is well present inside the container
        run: docker run -i --rm -v `pwd`/code:/newcode reanahub/reana-demo-bsm-search diff -r /code /newcode
