# This file is part of REANA.
# Copyright (C) 2020, 2021, 2023, 2024, 2026 CERN.
#
# REANA is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Pixi
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash
          echo "$HOME/.pixi/bin" >> "$GITHUB_PATH"

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install reana-client
          pip install reana-commons

      - name: Validate Snakemake workflow DAG
        run: pixi run snakemake-dry-run

      - name: Build analysis environment image
        run:
          docker build -f environments/reana-demo-bsm-search/Dockerfile -t
          reanahub/reana-demo-bsm-search .

      - name: Validate workflow specification file
        run: reana-client validate

      - name: Test whether the ROOT version is well 6
        run:
          docker run -i --rm -v `pwd`/code:/code reanahub/reana-demo-bsm-search
          root-config --version | grep -q ^6

      - name: Test whether we can import hftools Python library
        run:
          docker run -i --rm -v `pwd`/code:/code reanahub/reana-demo-bsm-search
          /bin/bash -c 'source /usr/local/bin/thisroot.sh && python -c "import
          hftools.hepdata"'

      - name:
          Test whether the latest analysis code is well present inside the
          container
        run:
          docker run -i --rm -v `pwd`/code:/newcode
          reanahub/reana-demo-bsm-search diff -r /code /newcode

  format-prettier:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Check Prettier code formatting
        run: |
          npm install prettier --global
          ./run-tests.sh --format-prettier

  format-shfmt:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check shell script code formatting
        run: |
          sudo apt-get install shfmt
          ./run-tests.sh --format-shfmt

  lint-commitlint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install commitlint
        run: |
          npm install conventional-changelog-conventionalcommits
          npm install commitlint@latest

      - name: Check commit message compliance of the recently pushed commit
        if: github.event_name == 'push'
        run: |
          ./run-tests.sh --lint-commitlint HEAD~1 HEAD

      - name: Check commit message compliance of the pull request
        if: github.event_name == 'pull_request'
        run: |
          ./run-tests.sh --lint-commitlint ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} ${{ github.event.pull_request.number }}

  lint-markdownlint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Lint Markdown files
        run: |
          npm install markdownlint-cli2 --global
          ./run-tests.sh --lint-markdownlint

  lint-shellcheck:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Runs shell script static analysis
        run: |
          sudo apt-get install shellcheck
          ./run-tests.sh --lint-shellcheck

  lint-yamllint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Lint YAML files
        run: |
          pip install yamllint
          ./run-tests.sh --lint-yamllint
